version: "3.1"
services:
    # auth:
    #     volumes:
    #         - ./auth:/usr/src/app

    ##──── blogwatcher ───────────────────────────────────────────────────────────────────────
    blogwatcher:
        stdin_open: true # docker run -i
        tty: true # docker run -t
        volumes:
            - ./blogWatcher:/usr/src/app
            - blogwatcher_dev_node_modules:/usr/src/app/node_modules # prevents host node_modules getting mounted
        ports:
            - "3000:3001" # publish ports to the host

    management:
        build:
            context: ./managementUI
            dockerfile: dockerfile
        stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
        container_name: management_dev
        expose:
            - "4000"
        volumes:
            - ./managementUI/frontend:/usr/src/app
            - management_ui_dev_node_modules:/usr/src/app/node_modules

# prevents the node_modules from being mapped to the host
# https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
volumes:
    blogwatcher_dev_node_modules:
        external: true
    blog_content:
        external: true
    blog_nginx_proxy_certs:
        external: true
    management_ui_dev_node_modules:
        external: true

networks:
    default:
        external:
            name: gateway_network
