version: "3.4"
services:
    blog_nginx_proxy:
        build:
            context: ./nginxProxy
            dockerfile: dockerfile
            target: production
        volumes:
            - blog_content:/usr/share/nginx/html
            - blog_nginx_proxy_certs:/etc/letsencrypt/live

    blogwatcher:
        build:
            context: ./blogWatcher
            dockerfile: dockerfile
            target: production

    blogbuilder:
        build:
            context: ./blogBuilder
            dockerfile: dockerfile

volumes:
    blog_content:
        external: true
