version: "3.4"
services:
    gateway:
        build:
            context: ./nginxProxy
            dockerfile: dockerfile
            target: production
        volumes:
            - blog_content:/usr/share/nginx/html
            - ./nginxProxy/keys/production:/etc/letsencrypt/live/

    blogwatcher:
        build:
            context: ./blogWatcher
            dockerfile: dockerfile
            target: production

    blogbuilder:
        build:
            context: ./blogBuilder
            dockerfile: dockerfile
            target: production

volumes:
    blog_content:
        external: true
